### ISSUE TITLE
Dockeriser le client

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#1]
## US

ETD je souhaite avoir un client dockerisé

cf [sandox](https://github.com/this-is-tobi/sandbox)

## TODO

- [x] Dockerfile dans client
- [x] docker-compose à la racine
- [x] séparer la partie e2e
