### ISSUE TITLE
Montée de version majeure eslint

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#1203]
## TODO

- [x] monter la version du paquet `eslint` dans tous les `package.json` où il est présent (dans VsCode, utiliser l'outil "show dependancies versions" en haut à droite du fichier
- [x] migrer les fichiers de configuration `eslintrc.json` selon la doc

## DOC
- https://eslint.org/docs/latest/use/configure/migration-guide#migrate-your-config-file
![image](https://github.com/cloud-pi-native/console/assets/71137721/92a5e556-5c9a-498e-8d6b-34cddfae0608)

### Définition du fini

- [ ] La fonctionnalité est terminée
- [ ] Les tests liés à cette fonctionnalité ont été ajoutés
- [ ] La documentation liée à cette fonctionnalité a été ajoutée (cf. https://github.com/cloud-pi-native/documentation)
- [ ] La communication avec les autres équipes impliquées par cette fonctionnalité a été faite
