### ISSUE TITLE
💡 [REQUEST] - Gestion de la config console (SystemSettings)

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#1318]
### Description

ETA je veux pouvoir modifier la config de la console.

## Liste des `SystemSettings`
- mode maintenance ✔️ 
- nom de l'application
- e-mail de contact ✔️ 
- texte sous le logo
- (url du logo)

### TODO
- front, page `/admin/system-setting`, formulaire dynamique selon settings remontés de la bdd
- gestion du cas où les clés n'existent pas en bdd

#### Surcharge dans l'ordre croissant :
- valeurs par défaut dans un JSON dans le code de la console
- possibilité d'uploader un JSON de config au déploiement de la console
- variable d'environnement correspondant à chaque setting
- lorsque l'admin modifie la config, elle est enregistrée en bdd

### Définition du fini

- [ ] La fonctionnalité est terminée
- [ ] Les tests liés à cette fonctionnalité ont été ajoutés
- [ ] La documentation liée à cette fonctionnalité a été ajoutée (cf. https://github.com/cloud-pi-native/documentation)
- [ ] La communication avec les autres équipes impliquées par cette fonctionnalité a été faite

**Comment by clairenollet** [comment]
https://github.com/this-is-tobi/template-monorepo-ts/blob/main/apps/api/src/utils/config.ts
