### ISSUE TITLE
Ajouter de la JSDoc dans le code

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#25]
## US
ETD je veux typer mon code pour qu'il soit plus robuste

## TODO
- [x] typer les paramètres que prennent les fonctions
- [x] typer les retours
- [x] ~voir si intéressant d'utiliser [https://github.com/vuese/vuese](https://github.com/vuese/vuese)~ => _roadmap pas maj depuis 4 ans_

## Ressources
[https://jsdoc.app/about-getting-started.html#getting-started](https://jsdoc.app/about-getting-started.html#getting-started)

```js
/**
 * Represents a book.
 * @constructor
 * @param {string} title - The title of the book.
 * @param {string} author - The author of the book.
 */
 ```
