### ISSUE TITLE
Implémenter AXIOS

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#30]
## TODO

- [x] installer axios
- [x] créer une instance d'axios dans un `xhr-client`
- [x] créer un fichier `api.js`
- [x] ajouter tests u qui vont avec
