### ISSUE TITLE
Synchro des organisations

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#436]
Page `admin/organizations` - bouton déclenche un `hook` récupérant les organisations auprès de canel et autres éventuels plugins

### client

- [x] ajout bouton et api `fetchOrganizations`

### server

- [x] création `hook` `fetchOrganizations`
- [x] register le plugin canel dessus

### tests

- [x] store
- [x] e2e
- [x] controller

### Todo CANEL

- en attente `slug` (servant à construire namespace)
