### ISSUE TITLE
Revoir règles UPSERT selon `status` et `locked`

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#444]
# TODO

- [x] doc business qu'est-ce qui se passe selon les `status` et `locked`
- [x] en cas de `projet.locked: true`, n'autoriser aucun `create` ni `update` sur toute ressource du projet
- [x] `Dashboard` affiche quelle ressource est en `status.failed`
- [x] Afficher la notion de verrouillage dans l'alerte info `selectedProject`

## Plus tard 
- A terme un bouton pour relancer les services qui ont échoué + un bouton pour recréer (détruire et reconstruire) - #457
