### ISSUE TITLE
Pouvoir transférer le rôle de `owner` 

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#552]
- Le `owner` doit pouvoir désigner un nouveau `owner` à sa place => il devient `user`, le membre désigné devient `owner`

# TODO

- [x] dans le tableau `DsoTeam.vue`, transformer les cellules `role` en `select` permettant de modifier le rôle de chaque membre.
- [ ] ajouter une zone de confirmation comme sur `ListOrganizations.vue`
- [ ] appeler `updateUserProjectRoleController`
- [ ] appeler le `hook` `upsertProject`
- [x] créer les actions correspondantes dans les plugins : lesquels sont concernés ? group keycloak spécial ou droits particuliers selon le rôle ? à affiner @ArnaudTA @this-is-tobi

**Comment by clairenollet** [comment]
> @clairenollet on ne voudra avoir qu'un seul `owner`, en revanche il faudra créer le rôle `coOwner` ou quelque chose dans le style (pour les `souscripteurs délégués`) qui ont les mêmes droits que le owner mais :
> 
>     * ne peuvent pas modifier les droits / retirer du projet le `owner`
> 
>     * ne peuvent pas supprimer le projet

#638
