### ISSUE TITLE
Créer l'utilisateur s'il n'existe pas quand on ajoute un membre au projet

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#562]
# TODO

- si `user where email == data.email` not found
- [x] get keycloak user
- [x] si not found, throw error
- [x] si found, create user in db and return
