### ISSUE TITLE
Environnements disponibles écrits en bdd

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#722]
# TODO

- [ ] Supprimer la `const allEnv` de `shared`
- [ ] Créer la table `DsoEnvironment`
- [ ] `Environment` s'y référence via un `DsoEnvironmentId`
- [ ] Ajouter page admin de modification / création de `DsoEnvironments`
- [ ] Pouvoir supprimer un `DsoEnvironment` ? Quelles conséquences pour le projet ?
